// AUTO-GENERATED by scripts/build-photos.mjs — do not edit by hand.
// Regenerate with `npm run photos`. Source: the ribafree photo pack
// manifest.json (kept outside this repo at ~/ribafree-photo-pack, not
// committed). Each top-level key in photosByTarget is a site_target id
// matching an id in src/config/content/portfolio.js (heldProperties or
// lots). sitePhotos holds page-chrome slots (hero/path cards), keyed to
// the SLOTS config above and consumed by src/config/images.js. Each slot
// entry has src480/src960 (standard tiers) plus srcNative (the source's
// own width, never upscaled — 1244 for the current three sources).

export const photosByTarget = {
  "wc1-hopes-lake": {
    "coverKind": "photo",
    "cover": {
      "src480": "/photos/1460-hopes-lake/exterior-1-480.webp",
      "src960": "/photos/1460-hopes-lake/exterior-1-960.webp",
      "w": 960,
      "h": 540,
      "alt": "Front exterior, 1460 Hopes Lake",
      "kind": "photo"
    },
    "gallery": [
      {
        "src480": "/photos/1460-hopes-lake/exterior-1-480.webp",
        "src960": "/photos/1460-hopes-lake/exterior-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Front exterior, 1460 Hopes Lake",
        "kind": "photo"
      },
      {
        "src480": "/photos/1460-hopes-lake/living-1-480.webp",
        "src960": "/photos/1460-hopes-lake/living-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Living area, 1460 Hopes Lake",
        "kind": "photo"
      },
      {
        "src480": "/photos/1460-hopes-lake/kitchen-1-480.webp",
        "src960": "/photos/1460-hopes-lake/kitchen-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Kitchen, 1460 Hopes Lake",
        "kind": "photo"
      },
      {
        "src480": "/photos/1460-hopes-lake/bedroom-1-480.webp",
        "src960": "/photos/1460-hopes-lake/bedroom-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Bedroom, 1460 Hopes Lake",
        "kind": "photo"
      },
      {
        "src480": "/photos/1460-hopes-lake/bath-1-480.webp",
        "src960": "/photos/1460-hopes-lake/bath-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Bathroom, 1460 Hopes Lake",
        "kind": "photo"
      }
    ],
    "floorPlans": [
      {
        "src480": "/photos/1460-hopes-lake/floorplan-1-480.webp",
        "src960": "/photos/1460-hopes-lake/floorplan-1-960.webp",
        "w": 960,
        "h": 1138,
        "alt": "Floor plan, 1460 Hopes Lake",
        "kind": "floorplan"
      }
    ]
  },
  "wc1-outpost-way": {
    "coverKind": "photo",
    "cover": {
      "src480": "/photos/1611-outpost-way/exterior-1-480.webp",
      "src960": "/photos/1611-outpost-way/exterior-1-960.webp",
      "w": 960,
      "h": 540,
      "alt": "Front exterior, 1611 Outpost Way",
      "kind": "photo"
    },
    "gallery": [
      {
        "src480": "/photos/1611-outpost-way/exterior-1-480.webp",
        "src960": "/photos/1611-outpost-way/exterior-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Front exterior, 1611 Outpost Way",
        "kind": "photo"
      },
      {
        "src480": "/photos/1611-outpost-way/living-1-480.webp",
        "src960": "/photos/1611-outpost-way/living-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Living area, 1611 Outpost Way",
        "kind": "photo"
      },
      {
        "src480": "/photos/1611-outpost-way/kitchen-1-480.webp",
        "src960": "/photos/1611-outpost-way/kitchen-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Kitchen, 1611 Outpost Way",
        "kind": "photo"
      },
      {
        "src480": "/photos/1611-outpost-way/bedroom-1-480.webp",
        "src960": "/photos/1611-outpost-way/bedroom-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Bedroom, 1611 Outpost Way",
        "kind": "photo"
      },
      {
        "src480": "/photos/1611-outpost-way/bath-1-480.webp",
        "src960": "/photos/1611-outpost-way/bath-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Bathroom, 1611 Outpost Way",
        "kind": "photo"
      }
    ],
    "floorPlans": [
      {
        "src480": "/photos/1611-outpost-way/floorplan-1-480.webp",
        "src960": "/photos/1611-outpost-way/floorplan-1-960.webp",
        "w": 960,
        "h": 902,
        "alt": "Floor plan, 1611 Outpost Way",
        "kind": "floorplan"
      }
    ]
  },
  "arbor-dr-princeton": {
    "coverKind": "photo",
    "cover": {
      "src480": "/photos/arbor-dr/exterior-1-480.webp",
      "src960": "/photos/arbor-dr/exterior-1-960.webp",
      "w": 960,
      "h": 720,
      "alt": "Front exterior, Arbor Dr",
      "kind": "photo"
    },
    "gallery": [
      {
        "src480": "/photos/arbor-dr/exterior-1-480.webp",
        "src960": "/photos/arbor-dr/exterior-1-960.webp",
        "w": 960,
        "h": 720,
        "alt": "Front exterior, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/living-1-480.webp",
        "src960": "/photos/arbor-dr/living-1-960.webp",
        "w": 960,
        "h": 720,
        "alt": "Living area, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/kitchen-1-480.webp",
        "src960": "/photos/arbor-dr/kitchen-1-960.webp",
        "w": 960,
        "h": 720,
        "alt": "Kitchen, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/kitchen-2-480.webp",
        "src960": "/photos/arbor-dr/kitchen-2-960.webp",
        "w": 960,
        "h": 720,
        "alt": "Kitchen, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/bedroom-1-480.webp",
        "src960": "/photos/arbor-dr/bedroom-1-960.webp",
        "w": 960,
        "h": 720,
        "alt": "Bedroom, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/bath-1-480.webp",
        "src960": "/photos/arbor-dr/bath-1-960.webp",
        "w": 864,
        "h": 1152,
        "alt": "Bathroom, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/bath-2-480.webp",
        "src960": "/photos/arbor-dr/bath-2-960.webp",
        "w": 864,
        "h": 1152,
        "alt": "Bathroom, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/utility-1-480.webp",
        "src960": "/photos/arbor-dr/utility-1-960.webp",
        "w": 864,
        "h": 1152,
        "alt": "Interior detail, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/utility-2-480.webp",
        "src960": "/photos/arbor-dr/utility-2-960.webp",
        "w": 960,
        "h": 720,
        "alt": "Interior detail, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/utility-3-480.webp",
        "src960": "/photos/arbor-dr/utility-3-960.webp",
        "w": 864,
        "h": 1152,
        "alt": "Interior detail, Arbor Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/arbor-dr/backyard-1-480.webp",
        "src960": "/photos/arbor-dr/backyard-1-960.webp",
        "w": 960,
        "h": 720,
        "alt": "Backyard, Arbor Dr",
        "kind": "photo"
      }
    ],
    "floorPlans": []
  },
  "sat-morning-ridge-aspen": {
    "coverKind": "rendering",
    "cover": {
      "src480": "/photos/morning-ridge-aspen/rendering-exterior-2-480.webp",
      "src960": "/photos/morning-ridge-aspen/rendering-exterior-2-960.webp",
      "w": 960,
      "h": 540,
      "alt": "Exterior rendering, Aspen (Elevation A)",
      "kind": "rendering"
    },
    "gallery": [
      {
        "src480": "/photos/morning-ridge-aspen/rendering-exterior-2-480.webp",
        "src960": "/photos/morning-ridge-aspen/rendering-exterior-2-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Exterior rendering, Aspen (Elevation A)",
        "kind": "rendering"
      },
      {
        "src480": "/photos/morning-ridge-aspen/rendering-exterior-1-480.webp",
        "src960": "/photos/morning-ridge-aspen/rendering-exterior-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Exterior rendering, Aspen (Elevation A)",
        "kind": "rendering"
      },
      {
        "src480": "/photos/morning-ridge-aspen/living-1-480.webp",
        "src960": "/photos/morning-ridge-aspen/living-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Living area, Aspen (Elevation A)",
        "kind": "photo"
      },
      {
        "src480": "/photos/morning-ridge-aspen/kitchen-1-480.webp",
        "src960": "/photos/morning-ridge-aspen/kitchen-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Kitchen, Aspen (Elevation A)",
        "kind": "photo"
      }
    ],
    "floorPlans": []
  },
  "wc2-oakcrest-ln": {
    "coverKind": "rendering",
    "cover": {
      "src480": "/photos/oakcrest-ln/rendering-exterior-1-480.webp",
      "src960": "/photos/oakcrest-ln/rendering-exterior-1-960.webp",
      "w": 960,
      "h": 540,
      "alt": "Exterior rendering, Oakcrest Ln",
      "kind": "rendering"
    },
    "gallery": [
      {
        "src480": "/photos/oakcrest-ln/rendering-exterior-1-480.webp",
        "src960": "/photos/oakcrest-ln/rendering-exterior-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Exterior rendering, Oakcrest Ln",
        "kind": "rendering"
      },
      {
        "src480": "/photos/oakcrest-ln/living-1-480.webp",
        "src960": "/photos/oakcrest-ln/living-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Living area, Oakcrest Ln",
        "kind": "photo"
      },
      {
        "src480": "/photos/oakcrest-ln/kitchen-1-480.webp",
        "src960": "/photos/oakcrest-ln/kitchen-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Kitchen, Oakcrest Ln",
        "kind": "photo"
      },
      {
        "src480": "/photos/oakcrest-ln/bedroom-1-480.webp",
        "src960": "/photos/oakcrest-ln/bedroom-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Bedroom, Oakcrest Ln",
        "kind": "photo"
      },
      {
        "src480": "/photos/oakcrest-ln/bath-1-480.webp",
        "src960": "/photos/oakcrest-ln/bath-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Bathroom, Oakcrest Ln",
        "kind": "photo"
      }
    ],
    "floorPlans": [
      {
        "src480": "/photos/oakcrest-ln/floorplan-1-480.webp",
        "src960": "/photos/oakcrest-ln/floorplan-1-960.webp",
        "w": 840,
        "h": 667,
        "alt": "Floor plan, Oakcrest Ln",
        "kind": "floorplan"
      }
    ]
  },
  "wc2-sabina-dr": {
    "coverKind": "photo",
    "cover": {
      "src480": "/photos/sabina-dr/exterior-1-480.webp",
      "src960": "/photos/sabina-dr/exterior-1-960.webp",
      "w": 960,
      "h": 540,
      "alt": "Front exterior, Sabina Dr",
      "kind": "photo"
    },
    "gallery": [
      {
        "src480": "/photos/sabina-dr/exterior-1-480.webp",
        "src960": "/photos/sabina-dr/exterior-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Front exterior, Sabina Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/sabina-dr/living-1-480.webp",
        "src960": "/photos/sabina-dr/living-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Living area, Sabina Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/sabina-dr/kitchen-1-480.webp",
        "src960": "/photos/sabina-dr/kitchen-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Kitchen, Sabina Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/sabina-dr/bedroom-1-480.webp",
        "src960": "/photos/sabina-dr/bedroom-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Bedroom, Sabina Dr",
        "kind": "photo"
      },
      {
        "src480": "/photos/sabina-dr/bath-1-480.webp",
        "src960": "/photos/sabina-dr/bath-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Bathroom, Sabina Dr",
        "kind": "photo"
      }
    ],
    "floorPlans": [
      {
        "src480": "/photos/sabina-dr/floorplan-1-480.webp",
        "src960": "/photos/sabina-dr/floorplan-1-960.webp",
        "w": 960,
        "h": 1276,
        "alt": "Floor plan, Sabina Dr",
        "kind": "floorplan"
      },
      {
        "src480": "/photos/sabina-dr/floorplan-2-480.webp",
        "src960": "/photos/sabina-dr/floorplan-2-960.webp",
        "w": 807,
        "h": 826,
        "alt": "Floor plan, Sabina Dr",
        "kind": "floorplan"
      }
    ]
  },
  "wc1-wildrose-way": {
    "coverKind": "rendering",
    "cover": {
      "src480": "/photos/wildrose-way/rendering-exterior-1-480.webp",
      "src960": "/photos/wildrose-way/rendering-exterior-1-960.webp",
      "w": 960,
      "h": 540,
      "alt": "Exterior rendering, WildRose Way",
      "kind": "rendering"
    },
    "gallery": [
      {
        "src480": "/photos/wildrose-way/rendering-exterior-1-480.webp",
        "src960": "/photos/wildrose-way/rendering-exterior-1-960.webp",
        "w": 960,
        "h": 540,
        "alt": "Exterior rendering, WildRose Way",
        "kind": "rendering"
      }
    ],
    "floorPlans": []
  }
}

export const sitePhotos = {
  "heroHome": {
    "src480": "/photos/site/heroHome-480.webp",
    "src960": "/photos/site/heroHome-960.webp",
    "srcNative": "/photos/site/heroHome-1244.webp",
    "w": 1244,
    "h": 700,
    "alt": "Brick two-story home with landscaped yard, aerial view",
    "kind": "photo"
  },
  "pathInvestor": {
    "src480": "/photos/site/pathInvestor-480.webp",
    "src960": "/photos/site/pathInvestor-960.webp",
    "srcNative": "/photos/site/pathInvestor-1244.webp",
    "w": 1244,
    "h": 700,
    "alt": "Aerial view of a residential community with a pool",
    "kind": "photo"
  },
  "pathBuyer": {
    "src480": "/photos/site/pathBuyer-480.webp",
    "src960": "/photos/site/pathBuyer-960.webp",
    "srcNative": "/photos/site/pathBuyer-1244.webp",
    "w": 1244,
    "h": 700,
    "alt": "Backyard of a brick single-story home",
    "kind": "photo"
  }
}
