// Every photo slot on the site, in one place. Every key here is a real
// photo, generated by scripts/build-photos.mjs (see its SLOTS config and
// PRODUCT.md's Photos section): heroHome/pathInvestor/pathBuyer from
// community-set photos the user authorized for general site-chrome use, and
// buyersHero/howItWorksSide/aboutSide/contactSide from real property-lot
// interior photos (their galleries exist but are never otherwise rendered
// anywhere in the UI, so these aren't shown twice). Each is an object
// ({ src480, src960, srcNative, w, h, alt, kind }), not a plain URL string.

import { sitePhotos } from './content/photos'

export const images = {
  // Real logo, provided by Talha 2026-07-19 ("classic logo-update jul18.png").
  // Full wordmark — light-on-transparent, meant for the dark site background.
  logo: '/ribafree-logo.png',

  // Home page — real photos (see note above)
  heroHome: sitePhotos.heroHome,
  pathInvestor: sitePhotos.pathInvestor,
  pathBuyer: sitePhotos.pathBuyer,

  // How It Works — real photo
  howItWorksSide: sitePhotos.howItWorksSide,

  // For Buyers — real photo
  buyersHero: sitePhotos.buyersHero,

  // About — real photo
  aboutSide: sitePhotos.aboutSide,

  // Contact — real photo
  contactSide: sitePhotos.contactSide,
}
