// Every photo slot on the site, in one place.
// Most values below are still Unsplash placeholders — swap any URL for a
// real property photo (local path or CDN URL) and the site updates
// everywhere. heroHome/pathInvestor/pathBuyer are the exception: real
// photos, generated by scripts/build-photos.mjs (see its SLOTS config and
// PRODUCT.md's Photos section) from community-set photos the user
// specifically authorized for this general site-chrome use. Each is an
// object ({ src480, src960, w, h, alt, kind }), not a plain URL string, so
// don't spread the `u()` pattern onto them.

import { sitePhotos } from './content/photos'

const u = (id, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`

export const images = {
  // Real logo, provided by Talha 2026-07-19 ("classic logo-update jul18.png").
  // Full wordmark — light-on-transparent, meant for the dark site background.
  logo: '/ribafree-logo.png',

  // Home page — real photos (see note above)
  heroHome: sitePhotos.heroHome,
  pathInvestor: sitePhotos.pathInvestor,
  pathBuyer: sitePhotos.pathBuyer,

  // How It Works
  howItWorksSide: u('photo-1600585154340-be6161a56a0c', 1000),

  // For Buyers
  buyersHero: u('photo-1580587771525-78b9dba3b914', 1400),

  // About
  aboutSide: u('photo-1600047509807-ba8f99d2cdde', 1000),

  // Contact
  contactSide: u('photo-1600566753190-17f0baa2a6c3', 1000),
}
