// Every photo slot on the site, in one place.
// contactSide is still an Unsplash placeholder — swap the URL for a real
// property photo (local path or CDN URL) and the site updates everywhere.
// Every other key here is a real photo, generated by scripts/build-photos.mjs
// (see its SLOTS config and PRODUCT.md's Photos section): heroHome/
// pathInvestor/pathBuyer from community-set photos the user authorized for
// general site-chrome use, and buyersHero/howItWorksSide/aboutSide from
// real property-lot interior photos (their galleries exist but are never
// otherwise rendered anywhere in the UI, so these aren't shown twice). Each
// is an object ({ src480, src960, srcNative, w, h, alt, kind }), not a plain
// URL string, so don't spread the `u()` pattern onto them.

import { sitePhotos } from './content/photos'

const u = (id, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`

export const images = {
  // Real logo, provided by Talha 2026-07-19 ("classic logo-update jul18.png").
  // Full wordmark — light-on-transparent, meant for the dark site background.
  logo: '/ribafree-logo.png',

  // Home page — real photos (see note above)
  heroHome: sitePhotos.heroHome,
  pathInvestor: sitePhotos.pathInvestor,
  pathBuyer: sitePhotos.pathBuyer,

  // How It Works — real photo
  howItWorksSide: sitePhotos.howItWorksSide,

  // For Buyers — real photo
  buyersHero: sitePhotos.buyersHero,

  // About — real photo
  aboutSide: sitePhotos.aboutSide,

  // Contact — still a stock placeholder
  contactSide: u('photo-1600566753190-17f0baa2a6c3', 1000),
}
